import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Offer Tariff",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-background text-foreground">
        {children}
      </body>
    </html>
  );
}
